### ISSUE TITLE
Power Card only outputs single additional hit

### ISSUE THREAD

**Issue by Kalosinn** [mrkeathley/DHRoll20Scripts#2]
Hi! I found your scripts yesterday and was very impressed with the level of automation in them. While I was testing it out with a few different weapons, I noticed that the Power Cards only output one additional hit regardless of the stated number of additional hits. 

![stormbolter](https://user-images.githubusercontent.com/109002773/178127291-a7ee620c-a9a5-43d3-bb1f-32bdf9a2c40b.png)

**Comment by mrkeathley** [comment]
I just happened to be on so I fixed this. It was due to power cards naming.

By the way - thanks! I'm glad someone else is testing this out finally so I can find the bugs I have been missing. I appreciate the help.

https://github.com/mrkeathley/DHRoll20Scripts/commit/3ed53fceb467e9db1c0cc3ef6c56b3dd14120fed

<img width="222" alt="multi-hit" src="https://user-images.githubusercontent.com/10247453/178128052-951b4435-0c0a-4ab1-a32b-217eb1ad743d.png">
